apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: ecom-secret-store
spec:
  provider:
    gcpsm:
      projectID: noble-linker-471623-s6
      auth:
        workloadIdentity:
          serviceAccountRef:
            name: {{.Values.ksaServiceAccount }}
            key: {{.Values.ksaServiceAccount}}