apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploymentName }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app: {{.Values.deploymentName }}
        version: {{ .Chart.AppVersion}}
#      name: {{.Values.deploymentName }}
    spec:
      imagePullSecrets:
        - name: regcred
      initContainers:
        - name: wait-for-secret-store
          image: bitnami/kubectl:latest
          imagePullPolicy: IfNotPresent
          command: ['sh', '-c']
          args:
            - |
              TARGET_SECRET_NAME='{{.Values.deploymentName}}-api-secret'
              NAMESPACE='{{.Values.namespace}}'
              echo "Waiting 20 seconds for K8s Secret $TARGET_SECRET_NAME to be created by ExternalSecrets Operator..."
              sleep 20
              echo "Secret $TARGET_SECRET_NAME found. Proceeding with main container."
      serviceAccountName: {{.Values.cicdKsaServiceAccount}}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.containerName }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.TargetPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            failureThreshold: 5
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            failureThreshold: 5
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: DB_HOST
              value: "127.0.0.1"
            - name: DB_PORT
              value: "5433"
            - name: DB_USER
              value: "postgres"
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: pgsql.password
                  name: '{{.Values.deploymentName}}-api-secret'
          volumeMounts:
            - name: {{.Values.deploymentName }}-config
              mountPath: /deployments/application-config
              readOnly: true
        # -- Cloud SQL Auth Proxy Sidecar Container ---
        - name: cloud-sql-proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:latest
          command:
            - "/cloud_sql_proxy"
            - "-ip_address_types=PUBLIC"
            - "-instances=noble-linker-471623-s6:us-central1:pg-instance=tcp:5433" # CloudSQL instance Connection name
          securityContext:
            runAsNonRoot: true
          resources:
            limits:
              memory: "128Mi"
              cpu: "250m"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
        - name: {{.Values.deploymentName }}-config
          configMap:
            name: {{.Values.deploymentName }}-config
            items:
              - key: application.yaml
                path: application.yaml
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - {{.Values.deploymentName }}
              topologyKey: {{.Values.topologyKey}}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
