apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploymentName }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app: {{.Values.deploymentName }}
        version: {{ .Chart.AppVersion}}
#      name: {{.Values.deploymentName }}
    spec:
      imagePullSecrets:
        - name: regcred
      initContainers:
        - name: wait-for-secret-store
          image: bitnami/kubectl:latest
          imagePullPolicy: IfNotPresent
          command: ['sh', '-c']
          args:
            - |
              TARGET_SECRET_NAME='{{.Values.deploymentName}}-api-secret'
              NAMESPACE='{{.Values.namespace}}'
              echo "Waiting for K8s Secret $TARGET_SECRET_NAME to be created by ExternalSecrets Operator..."
              
              while ! kubectl get secret $TARGET_SECRET_NAME -n $NAMESPACE > /dev/null 2>&1; do
                echo "Secret $TARGET_SECRET_NAME not found. Waiting 5 seconds..."
                sleep 5
              done
              echo "Secret $TARGET_SECRET_NAME found. Proceeding with main container."
      serviceAccountName: {{.Values.ksaServiceAccount }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.containerName }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.TargetPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            failureThreshold: 5
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            failureThreshold: 5
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: pgsql.password
                  name: '{{.Values.deploymentName}}-api-secret'
          volumeMounts:
            - name: {{.Values.deploymentName }}-config
              mountPath: /deployments/application-config
              readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
        - name: {{.Values.deploymentName }}-config
          configMap:
            name: {{.Values.deploymentName }}-config
            items:
              - key: application.yaml
                path: application.yaml
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - {{.Values.deploymentName }}
              topologyKey: {{.Values.topologyKey}}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
