apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{.Values.deploymentName}}-api-es
  namespace: {{.Values.namespace}}
spec:
  refreshInterval: '1h' # rate SecretManager pulls GSM
  secretStoreRef:
    name: ecom-secret-store  # name of the SecretStore
    kind: ClusterSecretStore
  target:
    name: {{.Values.deploymentName}}-api-secret # name of the K8s secret to be created
    creationPolicy: Owner
  data:
    {{ .Files.Get "resources/external-secret.yaml" | nindent 2}}