apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{.Values.namespace}}
  name: {{.Values.deploymentName}}-sa-pod-creator
rules:
  - apiGroups: [""]
    resource: ["*"]
    verbs: ["get", "watch", "list", "create", "update", "delete", "patch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{.Values.ksaServiceAccount}}
  namespace: {{.Values.namespace}}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.gcpServiceAccount }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{.Values.deploymentName}}-sa-pod-creator
  namespace: {{.Values.namespace}}
subjects:
  - kind: ServiceAccount
    name: {{.Values.deploymentName}}-sa
roleRef:
  kind: Role
  name: {{.Values.deploymentName}}-sa-pod-creator
  apiGroup: rbac.authorization.k8s.io