apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{.Values.deploymentName}}-secret-store
  namespace: {{.Values.namespace}}
spec:
  provider:
    gcpsm:
      projectID: noble-linker-471623-s6
      auth:
        workloadIdentity:
          serviceAccountRef:
            name: {{.Values.cicdKsaServiceAccount}}
            namespace: {{.Values.namespace}}