apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{.Values.deploymentName}}-secret-store
  namespace: {{.Values.namespace}}
spec:
  provider:
    clusterSecretStore:
      name: ecom-secret-store
    gcpsm:
      projectID: noble-linker-471623-s6
      auth:
        workloadIdentity:
          serviceAccountRef:
            name: external-secrets-sa
            namespace: external-secrets