name: "Upload Helm Package"

on:
  workflow_dispatch:
  pull_request:
    types: [closed]

permissions:
  id-token: write
  contents: write

env:
  BUCKET_NAME: "onlineliquorservices_bucket"
  ARTIFACTORY_REPO: "common-artifacts"
  APPLICATION_NAME: "ecom_helm"
  TARGET_ENV: "dev"

jobs:
  build:
    name: Package and Upload Helm Templates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.CI_CD_SA_SECRET }}

      - name: Common Setup for Artifactory Credentials & file version
        uses: ./.github/actions/common

      - name: Zip Helm templates
        run: |- 
          echo "Zipping helm templates..."
          zip -r ${APPLICATION_NAME}.zip helm/
          ls -lh ${APPLICATION_NAME}.zip

      - name: Upload .zip to GCS
        run: |-
          gsutil cp ${APPLICATION_NAME}.zip gs://${BUCKET_NAME}/${APPLICATION_NAME}/${TARGET_ENV}/${APPLICATION_NAME}.zip
